import 'package:flex_color_scheme/flex_color_scheme.dart';

final List<(FlexScheme scheme,FlexSchemeData color )> themes = [
  (FlexScheme.amber,FlexColor.amber),
  (FlexScheme.mallardGreen,FlexColor.mallardGreen),
  (FlexScheme.aquaBlue,FlexColor.aquaBlue),
  (FlexScheme.bahamaBlue,FlexColor.bahamaBlue),
  (FlexScheme.barossa,FlexColor.barossa),
  (FlexScheme.bigStone,FlexColor.bigStone),
  (FlexScheme.blue,FlexColor.blue),
  (FlexScheme.blueM3,FlexColor.blueM3),
  (FlexScheme.blueWhale,FlexColor.blueWhale),
  (FlexScheme.blumineBlue,FlexColor.blumineBlue),
  (FlexScheme.brandBlue,FlexColor.brandBlue),
  (FlexScheme.cyanM3,FlexColor.cyanM3),
  (FlexScheme.damask,FlexColor.damask),
  (FlexScheme.deepBlue,FlexColor.deepBlue),
  (FlexScheme.deepOrangeM3,FlexColor.deepOrangeM3),
  (FlexScheme.deepPurple,FlexColor.deepPurple),
  (FlexScheme.dellGenoa,FlexColor.dellGenoa),
  (FlexScheme.ebonyClay,FlexColor.ebonyClay),
  (FlexScheme.espresso,FlexColor.espresso),
  (FlexScheme.flutterDash,FlexColor.flutterDash),
  (FlexScheme.gold,FlexColor.gold),
  (FlexScheme.green,FlexColor.green),
  (FlexScheme.greenM3,FlexColor.greenM3),
  (FlexScheme.greyLaw,FlexColor.greyLaw),
  (FlexScheme.hippieBlue,FlexColor.hippieBlue),
  (FlexScheme.indigo,FlexColor.indigo),
  (FlexScheme.jungle,FlexColor.jungle),
  (FlexScheme.mandyRed,FlexColor.mandyRed),
  (FlexScheme.red,FlexColor.red),
  (FlexScheme.sakura,FlexColor.sakura),
];
